### ISSUE TITLE
Platform detection fails on RPi with arch linux arm

### ISSUE THREAD

**Issue by Keridos** [guyc/py-gaugette#24]
I get this error: 
Traceback (most recent call last):
  File "rotenctest.py", line 4, in <module>
    import gaugette.gpio
  File "/usr/lib/python3.6/site-packages/gaugette/gpio.py", line 12, in <module>
    import gaugette.platform
  File "/usr/lib/python3.6/site-packages/gaugette/platform.py", line 100, in <module>
    platform = platform_detect()
  File "/usr/lib/python3.6/site-packages/gaugette/platform.py", line 42, in platform_detect
    plat = platform.platform()
NameError: name 'platform' is not defined

with the default code for the program you have posted for a rotary encoder.

**Comment by guyc** [comment]
Is your hardware RPi3?

Can you post the results of `cat /proc/cpuinfo` please?

**Comment by guyc** [comment]
If it is a Pi3, PR #25 might solve the problem.

**Comment by Keridos** [comment]
No its a raspberry pi model B, the old one.

**Comment by guyc** [comment]
@Keridos are you able to provide the output from `cat /proc/cpuinfo`?

**Comment by guyc** [comment]
fixed in commit df9677863c9512b4d8c9ae32838d90973573efb9
